<?php

return [
    'autocomplete' => 'App\\Http\\Livewire\\Autocomplete',
    'dict.salutations-edit' => 'App\\Http\\Livewire\\Dict\\SalutationsEdit',
    'display-image' => 'App\\Http\\Livewire\\DisplayImage',
    'guest.kontakt' => 'App\\Http\\Livewire\\Guest\\Kontakt',
    'guest.navigation-top' => 'App\\Http\\Livewire\\Guest\\NavigationTop',
    'not-found' => 'App\\Http\\Livewire\\NotFound',
    'toggle-button' => 'App\\Http\\Livewire\\ToggleButton',
    'user.cost.detail' => 'App\\Http\\Livewire\\User\\Cost\\Detail',
    'user.cost.lista' => 'App\\Http\\Livewire\\User\\Cost\\Lista',
    'user.cost-amount.detail' => 'App\\Http\\Livewire\\User\\CostAmount\\Detail',
    'user.cost-amount.detail-input' => 'App\\Http\\Livewire\\User\\CostAmount\\DetailInput',
    'user.cost-amount.listitem' => 'App\\Http\\Livewire\\User\\CostAmount\\ListItem',
    'user.dialog.delete-modal' => 'App\\Http\\Livewire\\User\\Dialog\\DeleteModal',
    'user.navigation-top' => 'App\\Http\\Livewire\\User\\NavigationTop',
    'user.realestate.abrechnung.einstellungen' => 'App\\Http\\Livewire\\User\\Realestate\\Abrechnung\\Einstellungen',
    'user.realestate.header' => 'App\\Http\\Livewire\\User\\Realestate\\Header',
    'user.realestate.header-address' => 'App\\Http\\Livewire\\User\\Realestate\\HeaderAddress',
    'user.realestate.search-list' => 'App\\Http\\Livewire\\User\\Realestate\\SearchList',
    'user.realestate.verbrauchsinfo-user-email.detail' => 'App\\Http\\Livewire\\User\\Realestate\\VerbrauchsinfoUserEmail\\Detail',
    'user.realestate.verbrauchsinfo-user-email.detail-input' => 'App\\Http\\Livewire\\User\\Realestate\\VerbrauchsinfoUserEmail\\DetailInput',
    'user.realestate.verbrauchsinfo-user-email.listitem' => 'App\\Http\\Livewire\\User\\Realestate\\VerbrauchsinfoUserEmail\\ListItem',
    'user.realestate.verbrauchsinfo-user-email.search-list' => 'App\\Http\\Livewire\\User\\Realestate\\VerbrauchsinfoUserEmail\\SearchList',
    'user.realestate.verbrauchsinfo-user-emails' => 'App\\Http\\Livewire\\User\\Realestate\\VerbrauchsinfoUserEmails',
    'user.testing' => 'App\\Http\\Livewire\\User\\Testing',
    'user.occupant.counter-meter-reading.header' => 'App\\Http\\Livewire\\User\\occupant\\CounterMeterReading\\Header',
    'user.occupant.counter-meter-reading.listitem' => 'App\\Http\\Livewire\\User\\occupant\\CounterMeterReading\\ListItem',
    'user.occupant.counter-meter-reading.show-verbrauchsinfo-counter-meter-reading' => 'App\\Http\\Livewire\\User\\occupant\\CounterMeterReading\\ShowVerbrauchsinfoCounterMeterReading',
    'user.occupant.counter-meter.header' => 'App\\Http\\Livewire\\User\\occupant\\CounterMeter\\Header',
    'user.occupant.counter-meter.listitem' => 'App\\Http\\Livewire\\User\\occupant\\CounterMeter\\ListItem',
    'user.occupant.counter-meter.show-verbrauchsinfo-counter-meter' => 'App\\Http\\Livewire\\User\\occupant\\CounterMeter\\ShowVerbrauchsinfoCounterMeter',
    'user.occupant.occupant-header' => 'App\\Http\\Livewire\\User\\occupant\\OccupantHeader',
    'user.occupant.occupant-list' => 'App\\Http\\Livewire\\User\\occupant\\OccupantList',
    'user.occupant.occupants' => 'App\\Http\\Livewire\\User\\occupant\\Occupants',
    'user.occupant.search-list' => 'App\\Http\\Livewire\\User\\occupant\\SearchList',
    'user.occupant.verbrauchsinfo.header' => 'App\\Http\\Livewire\\User\\occupant\\Verbrauchsinfo\\Header',
    'user.occupant.verbrauchsinfo.listitem' => 'App\\Http\\Livewire\\User\\occupant\\Verbrauchsinfo\\ListItem',
    'user.occupant.verbrauchsinfo.occupant-view' => 'App\\Http\\Livewire\\User\\occupant\\Verbrauchsinfo\\OccupantView',
    'user.occupant.verbrauchsinfo.show-verbrauchsinfo' => 'App\\Http\\Livewire\\User\\occupant\\Verbrauchsinfo\\ShowVerbrauchsinfo',
    'user.occupant.verbrauchsinfo.show-verbrauchsinfos' => 'App\\Http\\Livewire\\User\\occupant\\Verbrauchsinfo\\ShowVerbrauchsinfos',
    'user.occupant.vorauszahlung-edit' => 'App\\Http\\Livewire\\User\\occupant\\VorauszahlungEdit',
];
