<x-guest-layout>
    <x-slot name="slot">
        <div class="px-4 py-6 mx-auto max-w-7xl sm:px-6 lg:px-8">

            <h2 class="py-2 text-2xl font-semibold leading-tight text-gray-800">
                RAUCHMELDERSERVICE
            </h2>
            <img class="w-full pt-2 pb-8 rounded-md " src="/img/home/Rauchmelderservice.jpg" alt="">
            <div>
                <p class="py-3">Vermieter, Mieter und selbstnutzende Eigentümer haben die Rauchwarnmelder-Pflicht zu beachten. Vermieter und selbstnutzende Eigentümer müssen Rauchwarnmelder in den Wohnungen einbauen und in Betrieb setzen. Wir beraten Sie gerne bei der Umsetzung der seit 31. Dezember 2013 bestehenden Rauchwarnmelder-Pflicht. Die fachgerechte Montage gehört selbstverständlich mit zu unserem Service.</p>
                <p class="py-3"><strong>Wer muss die Rauchwarnmelder-Pflicht beachten?</strong></p>
                <p class="py-3">Vermieter, Mieter und selbstnutzende Eigentümer haben die Rauchwarnmelder-Pflicht zu beachten. Vermieter und selbstnutzende Eigentümer müssen Rauchwarnmelder in den Wohnungen einbauen und in Betrieb setzen. Der Vermieter sollte sich vom Mieter den Einbau schriftlich bestätigen lassen. Bitte beachten Sie, dass die Rauchwarnmelder nicht von geschultem Fachpersonal angebracht werden müssen. Defekte Rauchwarnmelder sind vom Vermieter zu ersetzen. Bereits vom Mieter installierte Rauchwarnmelder dürfen, wenn der Vermieter zustimmt, weiter benutzt werden. Der Vermieter muss sich allerdings von der ordnungsgemäßen Installation und Betriebsbereitschaft überzeugen und sollte dies dokumentieren. Die Betriebsbereitschaft der Rauchwarnmelder hat der unmittelbare Besitzer, also der selbstnutzende Eigentümer bzw. der Mieter, sicherzustellen.</p>
                <p class="py-3"><strong>Welche Räume müssen mit Rauchwarnmeldern ausgestattet werden?</strong></p>
                <p class="py-3">Schlaf- und Kinderzimmer, sowie Flure, die als Rettungswege von Aufenthaltsräumen (z. B. Wohnzimmer) dienen, müssen mit mindestens einem Rauchwarnmelder ausgestattet werden. Zu Schlafzimmern zählen auch Einzimmerapartments. Wohnungen in Ein- und Mehrfamilienhäusern sind von der Rauchwarnmelder-Pflicht umfasst. In Kellern und Treppenhäusern außerhalb der Wohnung müssen keine Rauchwarnmelder installiert werden. Küche und Badezimmer müssen wegen Rauch und Wasserdampf ebenfalls nicht mit einem Rauchwarnmelder ausgestattet werden.</p>
                <p class="py-3"><strong>Bis wann müssen die Rauchwarnmelder eingebaut werden?</strong></p>
                <p class="py-3">In Wohnungen, die bis zum 31. März 2013 errichtet worden sind (Bestand), müssen bis zum 31. Dezember 2016 Rauchwarnmelder eingebaut werden. Wohnungen, die ab dem 1. April 2013 errichtet worden sind (Neubau), müssen von Anfang an mit Rauchwarnmeldern ausgestattet sein.</p>
                <p class="py-3"><strong>Wie sind die Rauchwarnmelder anzubringen?</strong></p>
                <p class="py-3">Die Rauchwarnmelder sind so anzubringen, dass der Brandrauch frühzeitig erkannt und gemeldet wird. Der Brandrauch muss den Rauchwarnmelder also ungehindert erreichen können. Grundsätzlich ist ein Rauchwarnmelder pro Raum ausreichend. Bei Räumen mit mehr als 60 m², bei verwinkelten Räumen oder sehr langen Fluren sind weitere Rauchwarnmelder erforderlich. Die Rauchwarnmelder sind mittig im Raum an der Decke und mindestens 50 cm von Wand, Unterzug oder Einrichtungsgegenständen anzubringen. Sofern besondere Einbaubedingungen bestehen (z. B. Dachschräge), sind weitere Anbringungsvarianten möglich. Hier gibt die Montageanleitung des Rauchwarnmelders Hinweise. Der Rauchwarnmelder kann mit Schrauben oder einem Klebepad an der Decke befestigt werden.</p>
                <p class="py-3"><strong>Welcher Rauchwarnmelder muss installiert werden?</strong></p>
                <p class="py-3">Der Mindestschutz ist mit batteriebetriebenen Rauchwarnmeldern gewährleistet. Es dürfen aber nur Rauchwarnmelder eingebaut werden, die nach der DIN EN 14604 in Verkehr gebracht wurden und ein entsprechendes CE-Zeichen tragen.</p>
                <p class="py-3"><strong>Welche Wartungspflicht haben Mieter und selbstnutzende Eigentümer?</strong></p>
                <p class="py-3">Der unmittelbare Besitzer der Wohnung, also der Mieter bzw. selbstnutzende Eigentümer, muss die Betriebsbereitschaft sicherstellen. Zu der Sicherstellung der Betriebsbereitschaft gehören die Funktionsprüfung, die Wartung sowie der Batteriewechsel. Als Funktionsprüfung ist das einmal jährliche Drücken der Prüftaste gemeint, um die akustische Warnung probeweise zu aktivieren. Sofern die Raucheindringungsöffnungen verschmutzt sein sollten, sind diese zu reinigen. Der Batteriewechsel hat nach Angaben des Herstellers zu erfolgen oder spätestens wenn der Rauchwarnmelder eine Batteriestörmeldung aussendet.</p>
                <p class="py-3"><strong>Trägt der Mieter die Kosten für die Installation und die Wartung von Rauchmeldern?</strong></p>
                <p class="py-3">Der Vermieter ist für Installation von Rauchwarnmeldern zuständig. Hierbei handelt es sich allerdings um eine Nachrüstverpflichtung, die der Vermieter nicht zu vertreten hat. Die Kosten, die dem Vermieter durch die erstmalige Installation von Rauchwarnmeldern im laufenden Mietverhältnis entstehen, können im Rahmen der Modernisierungsmieterhöhung gem. § 559 BGB (insgesamt maximal 11 Prozent jährlich der für die Wohnungaufgewendeten Kosten) auf den Mieter umgelegt werden. Hat sich der Vermieter darüber hinaus verpflichtet,die Wartung zu übernehmen, so kann er – sofern mietvertraglich vereinbart – die laufenden Betriebskosten aufden Mieter umlegen.</p>
                <p class="py-3"><strong>Was passiert, wenn der Mieter den Vermieter nicht in die Wohnung lässt?</strong></p>
                <p class="py-3">Um den Einbau von Rauchwarnmeldern in vermieteten Wohnungen zu ermöglichen, hat der Vermieter gem. § 555 d BGB unter bestimmten Voraussetzungen ein Betretungsrecht sowie der Mieter die Pflicht, die Modernisierungsmaßnahme zu dulden. Der Vermieter muss sein Betretungsrecht unter Umständen einklagen, sollte der Mieter die Gewährung des Zugangs zur Mietwohnung für Planung und Ausführung der Installation der Rauchwarnmelder nicht dulden.</p>
                <p class="py-3"><strong>Muss die Rauchwarnmelder-Pflicht befolgt werden?</strong></p>
                <p class="py-3">Die kommunalen Spitzenverbände haben bereits angekündigt, dass die kommunalen Behörden den Einbau und den Betrieb von Rauchwarnmeldern nicht kontrollieren werden. Allerdings kann es nicht ausgeschlossen werden, dass in Einzelfällen Bauordnungsämter auch auf Grund von Hinweisen Kontrollen durchführen werden. Da Sachschäden vom Schutzzweck der Rauchwarnmelder-Pflicht nicht erfasst sind, dürfte nach rechtlicher Einschätzung der nordrhein-westfälischen Landesregierung aber gegen Versicherungsklauseln von Sachversicherungen nicht verstoßen werden können.</p>
            </div>
        </div>
    </x-slot>
</x-guest-layout>

